apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      role: postgres
  template:
    metadata:
      labels:
        role: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - value: user
              name: POSTGRES_PASSWORD
            - value: user
              name: POSTGRES_USER
            - value: courses_db
              name: POSTGRES_DB
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data-postgres
      volumes:
        - name: data-postgres
          hostPath:
            path: /var/lib/postgresql/data
            type: DirectoryOrCreate