version: '3.8'

services:
  mysql8:
    image: mysql:8.0
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - spring
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: courses_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql/config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./postgresql/config/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    command: postgres -c config_file=/var/lib/postgresql/data/postgresql.conf
    networks:
      - spring
  ms-user:
    container_name: ms-user
    image: dockermsanchez/users:latest
    ports:
      - "8001:8001"
    env_file: ./ms-users/.env
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always
  ms-courses:
      container_name: ms-courses
      image: dockermsanchez/courses:latest
      ports:
        - "8002:8002"
      env_file:
        - ./ms-courses/.env
      networks:
        - spring
      depends_on:
        - postgres
        - ms-user
      restart: always
volumes:
  db_data:
  postgres_data:
networks:
  spring:
    name: spring