version: '3.8'

services:
  mysql8:
    image: mysql:8.0
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - spring
  postgres-db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: courses_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql/config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./postgresql/config/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    command: postgres -c config_file=/var/lib/postgresql/data/postgresql.conf
    networks:
      - spring
volumes:
  db_data:
  postgres_data:
networks:
  spring:
    name: spring