spring:
  cloud:
    gateway:
      routes:
        - id: oauth
          uri: lb://oauth
          predicates:
            - Path=/api/security/**
          filters:
            - StripPrefix=2
        - id: ms-user
          uri: lb://ms-user
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/user/(?<segment>.*), /$\{segment}
        - id: ms-courses
          uri: lb://ms-courses
          predicates:
            - Path=/api/courses/**
          filters:
            - StripPrefix=2