spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9100
      client:
        registration:
          client-app:
            provider: spring
            client-id: gateway-app
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8090/authorized
            scope:
              - openid
              - profile
            client-name: client-app
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9100
  cloud:
    gateway:
      routes:
        - id: oauth
          uri: lb://oauth
          predicates:
            - Path=/api/security/**
          filters:
            - StripPrefix=2
        - id: ms-user
          uri: lb://ms-user
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/user/(?<segment>.*), /$\{segment}
        - id: ms-courses
          uri: lb://ms-courses
          predicates:
            - Path=/api/courses/**
          filters:
            - StripPrefix=2