spring.application.name=ms-courses
server.port=8002
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/courses_db
spring.datasource.username=user
spring.datasource.password=user
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
logging.level.org.hibernate.SQL=debug

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true