spring.application.name=ms-courses
server.port=${PORT:8002}
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost:5432}/${DB_DATABASE:courses_db}
spring.datasource.username=${DB_USERNAME:user}
spring.datasource.password=${DB_PASSWORD:user}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
logging.level.org.hibernate.SQL=debug
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
ms.users.url=${USER_URL:ms-user:8001/api/user}
config.baseurl.endpoint.ms-users=http://localhost:8001