spring:
  application:
  name: ms-users
  server:
    port: 8001
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/user_db?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl: true
