spring:
  application:
    name: ms-user
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/user_db?allowPublicKeyRetrieval=false
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
server:
  port: ${PORT:8001}
logging:
  level:
    org:
      hibernate:
        SQL: debug