spring:
  application:
  name: ms-users
  server:
    port: 8001
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update